!--Variables de acceso al directorio activo de minminas--> prod anh.gov.co

ldap.url=ldap://192.168.70.157 
ldap.base=DC=anh,DC=gov,DC=co
ldap.userDn=sso
ldap.password=Anh.ss0*
ldap.base.schema=
ldap.directoryString=sAMAccountName 