database_engine = ${database_engine}
database.context.name = ${context_name}
files_path = /opt/data/files
email.activation.template = activation-account.html
email.activation.url =  ${domain}
email.restore.password.template = restore-password-account.html
email.restore.password.url = ${domain}
email.company = APP
email.logo.url = https://www.domain.gov.co/img/logos/logo.png
email.app.name = ${appName}
